### ISSUE TITLE
Unexpected Keyword Argument 'options'

### ISSUE THREAD

**Issue by UnityEQ** [sowdust/ffff#4]
Just setting this up, getting the error below and not sure why. Any advice?

Traceback (most recent call last):
  File "ffff.py", line 407, in <module>
    main()
  File "ffff.py", line 370, in main
    driver = webdriver.Firefox(executable_path=driver_path,options=options)
TypeError: __init__() got an unexpected keyword argument 'options'

**Comment by UnityEQ** [comment]
Changed it to:

from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary('C:\Program Files\Mozilla Firefox\Firefox.exe')
driver = webdriver.Firefox(firefox_binary=binary)

getting this error now:

Traceback (most recent call last):
  File "ffff.py", line 410, in <module>
    main()
  File "ffff.py", line 373, in main
    driver = webdriver.Firefox(firefox_binary=binary)
  File "C:\Users\Danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 98, in __init__
    self.binary, timeout)
  File "C:\Users\Danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "C:\Users\Danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "C:\Users\Danie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by sowdust** [comment]
what version of selenium are you using?
