### ISSUE TITLE
cannot get it working

### ISSUE THREAD

**Issue by jbdu94** [sowdust/ffff#6]
Hello

I get the following error
selenium.common.exceptions.WebDriverException: Message: permission denied

what am I doing wrong?
here is my query
ffff.py -fu myemail@myemail.com -fp mypassword -t 100003339235687 -p 100005022796967 -o result.txt -g result -d C:\Users\JB\Downloads\geckodriver.exe

Here is the full track
Traceback (most recent call last):
  File "C:\Users\Laurence\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Laurence\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Laurence\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Accès refusé

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ffff.py", line 424, in <module>
    main()
  File "ffff.py", line 387, in main
    driver = webdriver.Firefox(executable_path=driver_path,options=options)
  File "C:\Users\Laurence\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\Laurence\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'Downloads' executable may have wrong permissions.

Many thx for your help!

**Comment by sowdust** [comment]
Hi, looking at the error, it seems as Windows is complaining about the current user not having permissions to execute the geckodriver file.
The final line also suggests so: " selenium.common.exceptions.WebDriverException: Message: 'Downloads' executable may have wrong permissions.".
Maybe it's because geckodriver executable is in JB's area, while the script trying to run it is in Laurence's area. Try to move geckodriver in a folder owned by user Laurence and modify the command line accordingly.
